apiVersion: v1
kind: Service
metadata:
  name: ecs-manager
  namespace: ecs-platform
  labels:
    app: ecs-manager
spec:
  type: NodePort
  selector:
    app: ecs-manager
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
